### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mfuchs1984** [vanhauser-thc/vulntest#2]
To use and modify the code to test and compare more static analysis tools, a license would be helpful, especially for cloud based tools.

**Comment by vanhauser-thc** [comment]
the issue is that there is one cpp file that I took from the NIST c/c++ juliet test library. which has no documented license.
As other packages there are BSD I gonna assume its BSD too, so setting this to BSD

**Comment by mfuchs1984** [comment]
Thanks much
